import { useState } from "react";
import { AgGridReact } from "ag-grid-react";
import { AllCommunityModule, ModuleRegistry } from "ag-grid-community";
import DeleteIcon from "@mui/icons-material/Delete";

// Register all Community features
ModuleRegistry.registerModules([AllCommunityModule]);

function AgChart() {
  //store data starts here
  const [storeRowData] = useState<any>([
    {
      id: "ST035",
      label: "San Francisco Bay Trends",
      city: "San Francisco",
      state: "CA",
    },
    {
      id: "ST046",
      label: "Phoenix Sunwear",
      city: "Phoenix",
      state: "AZ",
    },
    {
      id: "ST064",
      label: "Dallas Ranch Supply",
      city: "Dallas",
      state: "TX",
    },
    {
      id: "ST066",
      label: "Atlanta Outfitters",
      city: "Atlanta",
      state: "GA",
    },
    {
      id: "ST073",
      label: "Nashville Melody Music Store",
      city: "Nashville",
      state: "TN",
    },
    {
      id: "ST074",
      label: "New York Empire Eats",
      city: "New York",
      state: "NY",
    },
    {
      id: "ST091",
      label: "Denver Peaks Outdoor",
      city: "Denver",
      state: "CO",
    },
    {
      id: "ST094",
      label: "Philadelphia Liberty Market",
      city: "Philadelphia",
      state: "PA",
    },
    {
      id: "ST097",
      label: "Boston Harbor Books",
      city: "Boston",
      state: "MA",
    },
    {
      id: "ST101",
      label: "Austin Vibe Co.",
      city: "Austin",
      state: "TX",
    },
    {
      id: "ST131",
      label: "Los Angeles Luxe",
      city: "Los Angeles",
      state: "CA",
    },
    {
      id: "ST150",
      label: "Houston Harvest Market",
      city: "Houston",
      state: "TX",
    },
    {
      id: "ST151",
      label: "Portland Evergreen Goods",
      city: "Portland",
      state: "OR",
    },
    {
      id: "ST156",
      label: "Chicago Charm Boutique",
      city: "Chicago",
      state: "IL",
    },
    {
      id: "ST163",
      label: "Las Vegas Neon Treasures",
      city: "Las Vegas",
      state: "NV",
    },
    {
      id: "ST175",
      label: "Seattle Skyline Goods",
      city: "Seattle",
      state: "WA",
    },
    {
      id: "ST176",
      label: "Miami Breeze Apparel",
      city: "Miami",
      state: "FL",
    },
    {
      id: "ST177",
      label: "San Diego Wave Surf Shop",
      city: "San Diego",
      state: "CA",
    },
    {
      id: "ST193",
      label: "Charlotte Queen's Closet",
      city: "Charlotte",
      state: "NC",
    },
    {
      id: "ST208",
      label: "Detroit Motor Gear",
      city: "Detroit",
      state: "MI",
    },
  ]);

  const [storeColDefs] = useState<any>([
    {
      headerName: "",
      cellRenderer: function (param) {
        return <DeleteIcon onClick={()=>console.log(param.data.id)}/>;
      },width:60
    },
    {
      headerName: "S.No.",
      valueGetter: "node.rowIndex + 1",
    },
    { field: "label", flex: 1 , headerName: "Store",},
    { field: "city", flex: 1 },
    { field: "state", flex: 1 },
  ]);
  //store data ends here

  //sku data starts here
  const [sku] = useState<any>([
    {
      sku: "SK00158",
      label: "Crew Neck Merino Wool Sweater",
      class: "Tops",
      department: "Men's Apparel",
      price: 114.99,
      cost: 18.28,
    },
    {
      sku: "SK00269",
      label: "Faux Leather Leggings",
      class: "Jewelry",
      department: "Footwear",
      price: 9.99,
      cost: 8.45,
    },
    {
      sku: "SK00300",
      label: "Fleece-Lined Parka",
      class: "Jewelry",
      department: "Unisex Accessories",
      price: 199.99,
      cost: 17.8,
    },
    {
      sku: "SK00304",
      label: "Cotton Polo Shirt",
      class: "Tops",
      department: "Women's Apparel",
      price: 139.99,
      cost: 10.78,
    },
    {
      sku: "SK00766",
      label: "Foldable Travel Hat",
      class: "Tops",
      department: "Footwear",
      price: 44.99,
      cost: 27.08,
    },
    {
      sku: "SK00786",
      label: "Chic Quilted Wallet",
      class: "Bottoms",
      department: "Footwear",
      price: 14.99,
      cost: 4.02,
    },
    {
      sku: "SK00960",
      label: "High-Slit Maxi Dress",
      class: "Outerwear",
      department: "Sportswear",
      price: 74.99,
      cost: 47.47,
    },
    {
      sku: "SK01183",
      label: "Turtleneck Cable Knit Sweater",
      class: "Footwear",
      department: "Footwear",
      price: 49.99,
      cost: 22.6,
    },
    {
      sku: "SK01189",
      label: "Retro-Inspired Sunglasses",
      class: "Bottoms",
      department: "Women's Apparel",
      price: 194.99,
      cost: 115.63,
    },
    {
      sku: "SK01193",
      label: "Stretch Denim Overalls",
      class: "Bottoms",
      department: "Unisex Accessories",
      price: 129.99,
      cost: 47.06,
    },
    {
      sku: "SK01249",
      label: "Adjustable Elastic Headband",
      class: "Footwear",
      department: "Women's Apparel",
      price: 19.99,
      cost: 1.34,
    },
    {
      sku: "SK01319",
      label: "Adjustable Baseball Cap",
      class: "Jewelry",
      department: "Men's Apparel",
      price: 4.99,
      cost: 2.29,
    },
    {
      sku: "SK01349",
      label: "Cotton Polo Shirt",
      class: "Bottoms",
      department: "Unisex Accessories",
      price: 114.99,
      cost: 60.94,
    },
    {
      sku: "SK01549",
      label: "Faux Suede Ankle Boots",
      class: "Tops",
      department: "Sportswear",
      price: 94.99,
      cost: 71.53,
    },
    {
      sku: "SK01566",
      label: "Striped Cotton Socks",
      class: "Accessories",
      department: "Sportswear",
      price: 9.99,
      cost: 6.91,
    },
    {
      sku: "SK01642",
      label: "Performance Compression Tights",
      class: "Outerwear",
      department: "Sportswear",
      price: 54.99,
      cost: 59.61,
    },
    {
      sku: "SK01733",
      label: "Vintage Logo Hoodie",
      class: "Accessories",
      department: "Men's Apparel",
      price: 94.99,
      cost: 84.45,
    },
    {
      sku: "SK01896",
      label: "Floral Chiffon Wrap Dress",
      class: "Accessories",
      department: "Unisex Accessories",
      price: 149.99,
      cost: 68.55,
    },
    {
      sku: "SK01927",
      label: "Asymmetrical Hem Skirt",
      class: "Jewelry",
      department: "Sportswear",
      price: 99.99,
      cost: 66.89,
    },
    {
      sku: "SK01950",
      label: "Slim Fit Pinstripe Suit",
      class: "Bottoms",
      department: "Women's Apparel",
      price: 99.99,
      cost: 13.3,
    },
    {
      sku: "SK02029",
      label: "Chunky Heel Sandals",
      class: "Jewelry",
      department: "Unisex Accessories",
      price: 89.99,
      cost: 46.7,
    },
    {
      sku: "SK02429",
      label: "Suede Fringe Vest",
      class: "Bottoms",
      department: "Footwear",
      price: 184.99,
      cost: 159.65,
    },
    {
      sku: "SK02448",
      label: "Relaxed Fit Cargo Pants",
      class: "Bottoms",
      department: "Sportswear",
      price: 149.99,
      cost: 7.2,
    },
    {
      sku: "SK02562",
      label: "Corduroy A-Line Skirt",
      class: "Jewelry",
      department: "Footwear",
      price: 129.99,
      cost: 48.62,
    },
    {
      sku: "SK02642",
      label: "Formal Dress Shoes",
      class: "Bottoms",
      department: "Women's Apparel",
      price: 164.99,
      cost: 161.69,
    },
    {
      sku: "SK02768",
      label: "Tailored Corduroy Blazer",
      class: "Accessories",
      department: "Sportswear",
      price: 89.99,
      cost: 62.99,
    },
    {
      sku: "SK02805",
      label: "Foldable Travel Hat",
      class: "Outerwear",
      department: "Women's Apparel",
      price: 194.99,
      cost: 56.16,
    },
    {
      sku: "SK02904",
      label: "Asymmetrical Hem Skirt",
      class: "Tops",
      department: "Unisex Accessories",
      price: 89.99,
      cost: 67.94,
    },
    {
      sku: "SK03182",
      label: "Plaid Flannel Shirt",
      class: "Tops",
      department: "Unisex Accessories",
      price: 124.99,
      cost: 17.5,
    },
    {
      sku: "SK03289",
      label: "Oversized Hoodie",
      class: "Tops",
      department: "Women's Apparel",
      price: 159.99,
      cost: 122.23,
    },
    {
      sku: "SK03348",
      label: "Woven Straw Sun Hat",
      class: "Jewelry",
      department: "Footwear",
      price: 164.99,
      cost: 8.91,
    },
    {
      sku: "SK03569",
      label: "Faux Fur Winter Coat",
      class: "Tops",
      department: "Men's Apparel",
      price: 9.99,
      cost: 7.37,
    },
    {
      sku: "SK03572",
      label: "Casual Cotton Romper",
      class: "Tops",
      department: "Footwear",
      price: 119.99,
      cost: 52.32,
    },
    {
      sku: "SK03636",
      label: "Racerback Sports Bra",
      class: "Footwear",
      department: "Unisex Accessories",
      price: 14.99,
      cost: 8.72,
    },
    {
      sku: "SK03725",
      label: "Polarized Sports Sunglasses",
      class: "Tops",
      department: "Men's Apparel",
      price: 79.99,
      cost: 9.44,
    },
    {
      sku: "SK03980",
      label: "Chunky Platform Sneakers",
      class: "Tops",
      department: "Unisex Accessories",
      price: 109.99,
      cost: 61.7,
    },
    {
      sku: "SK04282",
      label: "Slim Fit Chinos",
      class: "Footwear",
      department: "Sportswear",
      price: 114.99,
      cost: 51.98,
    },
    {
      sku: "SK04325",
      label: "Faux Leather Leggings",
      class: "Tops",
      department: "Footwear",
      price: 194.99,
      cost: 13.06,
    },
    {
      sku: "SK04707",
      label: "Water-Resistant Fanny Pack",
      class: "Tops",
      department: "Women's Apparel",
      price: 24.99,
      cost: 23.64,
    },
    {
      sku: "SK04815",
      label: "Performance Compression Tights",
      class: "Bottoms",
      department: "Footwear",
      price: 14.99,
      cost: 16.29,
    },
    {
      sku: "SK05097",
      label: "Cropped Faux Leather Jacket",
      class: "Jewelry",
      department: "Sportswear",
      price: 79.99,
      cost: 19.52,
    },
    {
      sku: "SK05194",
      label: "Breathable Mesh Shorts",
      class: "Accessories",
      department: "Footwear",
      price: 194.99,
      cost: 28.08,
    },
    {
      sku: "SK05478",
      label: "Minimalist Silver Ring",
      class: "Accessories",
      department: "Footwear",
      price: 174.99,
      cost: 147.34,
    },
    {
      sku: "SK05715",
      label: "Ribbed Turtleneck Dress",
      class: "Bottoms",
      department: "Footwear",
      price: 94.99,
      cost: 22.61,
    },
    {
      sku: "SK05928",
      label: "Velvet Slip Dress",
      class: "Jewelry",
      department: "Men's Apparel",
      price: 69.99,
      cost: 41.64,
    },
    {
      sku: "SK06290",
      label: "Waterproof Smartwatch",
      class: "Bottoms",
      department: "Men's Apparel",
      price: 144.99,
      cost: 53.5,
    },
    {
      sku: "SK06375",
      label: "Patterned Cotton Bucket Hat",
      class: "Outerwear",
      department: "Sportswear",
      price: 144.99,
      cost: 114.4,
    },
    {
      sku: "SK06559",
      label: "Diamond Stud Earrings",
      class: "Outerwear",
      department: "Men's Apparel",
      price: 144.99,
      cost: 146.0,
    },
    {
      sku: "SK06601",
      label: "Tassel Fringe Handbag",
      class: "Outerwear",
      department: "Unisex Accessories",
      price: 59.99,
      cost: 33.29,
    },
    {
      sku: "SK06651",
      label: "Tactical Hiking Backpack",
      class: "Outerwear",
      department: "Sportswear",
      price: 49.99,
      cost: 52.54,
    },
    {
      sku: "SK06691",
      label: "Patterned Cotton Bucket Hat",
      class: "Accessories",
      department: "Unisex Accessories",
      price: 9.99,
      cost: 2.14,
    },
    {
      sku: "SK06996",
      label: "Bohemian Beaded Bracelet",
      class: "Accessories",
      department: "Unisex Accessories",
      price: 124.99,
      cost: 116.12,
    },
    {
      sku: "SK07054",
      label: "Mesh Panel Yoga Pants",
      class: "Accessories",
      department: "Footwear",
      price: 184.99,
      cost: 166.86,
    },
    {
      sku: "SK07068",
      label: "Diamond Stud Earrings",
      class: "Outerwear",
      department: "Sportswear",
      price: 14.99,
      cost: 13.75,
    },
    {
      sku: "SK07322",
      label: "Faux Suede Ankle Boots",
      class: "Tops",
      department: "Footwear",
      price: 84.99,
      cost: 90.43,
    },
    {
      sku: "SK07369",
      label: "Water-Resistant Fanny Pack",
      class: "Outerwear",
      department: "Unisex Accessories",
      price: 4.99,
      cost: 3.73,
    },
    {
      sku: "SK07447",
      label: "Plaid Wool Scarf",
      class: "Tops",
      department: "Footwear",
      price: 139.99,
      cost: 97.57,
    },
    {
      sku: "SK07484",
      label: "Cropped Faux Leather Jacket",
      class: "Accessories",
      department: "Women's Apparel",
      price: 179.99,
      cost: 163.43,
    },
    {
      sku: "SK07595",
      label: "Textured Knit Pullover",
      class: "Tops",
      department: "Footwear",
      price: 54.99,
      cost: 50.43,
    },
    {
      sku: "SK07767",
      label: "Boho Style Tassel Earrings",
      class: "Footwear",
      department: "Sportswear",
      price: 194.99,
      cost: 193.43,
    },
    {
      sku: "SK07782",
      label: "Sherpa Lined Hooded Coat",
      class: "Jewelry",
      department: "Footwear",
      price: 174.99,
      cost: 128.09,
    },
    {
      sku: "SK07944",
      label: "Mesh Panel Yoga Pants",
      class: "Tops",
      department: "Unisex Accessories",
      price: 69.99,
      cost: 45.49,
    },
    {
      sku: "SK08191",
      label: "Graphic Print T-Shirt",
      class: "Jewelry",
      department: "Men's Apparel",
      price: 109.99,
      cost: 53.35,
    },
    {
      sku: "SK08285",
      label: "Fitted V-Neck Sweater",
      class: "Footwear",
      department: "Men's Apparel",
      price: 124.99,
      cost: 110.24,
    },
    {
      sku: "SK08314",
      label: "Formal Dress Shoes",
      class: "Accessories",
      department: "Footwear",
      price: 74.99,
      cost: 8.62,
    },
    {
      sku: "SK08373",
      label: "Satin Lace Camisole",
      class: "Jewelry",
      department: "Women's Apparel",
      price: 184.99,
      cost: 136.15,
    },
    {
      sku: "SK08443",
      label: "Slim Fit Chinos",
      class: "Bottoms",
      department: "Unisex Accessories",
      price: 89.99,
      cost: 61.64,
    },
    {
      sku: "SK08544",
      label: "Retro-Inspired Sunglasses",
      class: "Footwear",
      department: "Women's Apparel",
      price: 44.99,
      cost: 41.12,
    },
    {
      sku: "SK08557",
      label: "Formal Velvet Blazer",
      class: "Bottoms",
      department: "Sportswear",
      price: 194.99,
      cost: 189.14,
    },
    {
      sku: "SK08783",
      label: "Striped Cotton Socks",
      class: "Accessories",
      department: "Footwear",
      price: 169.99,
      cost: 10.54,
    },
    {
      sku: "SK09245",
      label: "Yoga Leggings",
      class: "Bottoms",
      department: "Unisex Accessories",
      price: 164.99,
      cost: 172.58,
    },
    {
      sku: "SK09312",
      label: "Formal Dress Shoes",
      class: "Bottoms",
      department: "Sportswear",
      price: 9.99,
      cost: 1.96,
    },
    {
      sku: "SK09318",
      label: "Aviator Sunglasses",
      class: "Footwear",
      department: "Sportswear",
      price: 44.99,
      cost: 12.37,
    },
    {
      sku: "SK09414",
      label: "Perforated Leather Belt",
      class: "Tops",
      department: "Footwear",
      price: 44.99,
      cost: 4.5,
    },
    {
      sku: "SK09453",
      label: "Smart Heated Gloves",
      class: "Footwear",
      department: "Unisex Accessories",
      price: 109.99,
      cost: 100.53,
    },
    {
      sku: "SK09469",
      label: "Silk Embroidered Kimono",
      class: "Jewelry",
      department: "Sportswear",
      price: 109.99,
      cost: 78.64,
    },
    {
      sku: "SK09592",
      label: "Performance Swim Trunks",
      class: "Tops",
      department: "Men's Apparel",
      price: 174.99,
      cost: 157.84,
    },
    {
      sku: "SK09659",
      label: "Tactical Hiking Backpack",
      class: "Jewelry",
      department: "Women's Apparel",
      price: 69.99,
      cost: 58.16,
    },
    {
      sku: "SK09728",
      label: "Thermal Running Gloves",
      class: "Outerwear",
      department: "Women's Apparel",
      price: 49.99,
      cost: 53.79,
    },
    {
      sku: "SK09816",
      label: "Quilted Leather Clutch",
      class: "Jewelry",
      department: "Unisex Accessories",
      price: 134.99,
      cost: 95.84,
    },
    {
      sku: "SK10226",
      label: "Rugged Utility Jacket",
      class: "Accessories",
      department: "Unisex Accessories",
      price: 44.99,
      cost: 2.43,
    },
    {
      sku: "SK10286",
      label: "Tapered Suit Trousers",
      class: "Bottoms",
      department: "Men's Apparel",
      price: 64.99,
      cost: 53.1,
    },
    {
      sku: "SK10304",
      label: "Faux Leather Leggings",
      class: "Tops",
      department: "Men's Apparel",
      price: 139.99,
      cost: 22.54,
    },
    {
      sku: "SK10514",
      label: "Lace-Up Combat Boots",
      class: "Tops",
      department: "Sportswear",
      price: 109.99,
      cost: 64.89,
    },
    {
      sku: "SK10565",
      label: "Athletic Crew Socks",
      class: "Accessories",
      department: "Unisex Accessories",
      price: 174.99,
      cost: 1.75,
    },
    {
      sku: "SK10717",
      label: "Silk Neck Scarf",
      class: "Outerwear",
      department: "Footwear",
      price: 94.99,
      cost: 49.87,
    },
    {
      sku: "SK10760",
      label: "Sherpa Lined Denim Jacket",
      class: "Outerwear",
      department: "Women's Apparel",
      price: 119.99,
      cost: 28.92,
    },
    {
      sku: "SK11103",
      label: "Lace-Up Combat Boots",
      class: "Outerwear",
      department: "Men's Apparel",
      price: 24.99,
      cost: 24.84,
    },
    {
      sku: "SK11147",
      label: "Sporty Zip-Up Hoodie",
      class: "Footwear",
      department: "Women's Apparel",
      price: 184.99,
      cost: 65.3,
    },
    {
      sku: "SK11260",
      label: "Minimalist Gold Necklace",
      class: "Footwear",
      department: "Unisex Accessories",
      price: 104.99,
      cost: 52.08,
    },
    {
      sku: "SK11808",
      label: "Classic Denim Jacket",
      class: "Jewelry",
      department: "Women's Apparel",
      price: 149.99,
      cost: 144.29,
    },
    {
      sku: "SK11860",
      label: "Tassel Fringe Handbag",
      class: "Accessories",
      department: "Sportswear",
      price: 109.99,
      cost: 3.19,
    },
    {
      sku: "SK12148",
      label: "Oversized Cat-Eye Sunglasses",
      class: "Jewelry",
      department: "Footwear",
      price: 159.99,
      cost: 109.11,
    },
    {
      sku: "SK12418",
      label: "Minimalist Leather Watch",
      class: "Bottoms",
      department: "Unisex Accessories",
      price: 49.99,
      cost: 49.89,
    },
    {
      sku: "SK12460",
      label: "Quilted Leather Clutch",
      class: "Bottoms",
      department: "Unisex Accessories",
      price: 4.99,
      cost: 0.68,
    },
    {
      sku: "SK12478",
      label: "Floral Chiffon Wrap Dress",
      class: "Footwear",
      department: "Men's Apparel",
      price: 184.99,
      cost: 39.59,
    },
    {
      sku: "SK12670",
      label: "Graphic Skateboard Tee",
      class: "Bottoms",
      department: "Women's Apparel",
      price: 194.99,
      cost: 53.43,
    },
    {
      sku: "SK12760",
      label: "Minimalist Silver Ring",
      class: "Tops",
      department: "Unisex Accessories",
      price: 9.99,
      cost: 9.53,
    },
    {
      sku: "SK12773",
      label: "Padded Winter Mittens",
      class: "Tops",
      department: "Unisex Accessories",
      price: 154.99,
      cost: 53.78,
    },
    {
      sku: "SK12919",
      label: "Classic Denim Jacket",
      class: "Jewelry",
      department: "Footwear",
      price: 109.99,
      cost: 89.53,
    },
    {
      sku: "SK13050",
      label: "Lace-Up Combat Boots",
      class: "Tops",
      department: "Women's Apparel",
      price: 134.99,
      cost: 75.59,
    },
    {
      sku: "SK13226",
      label: "Cuffed Jogger Pants",
      class: "Jewelry",
      department: "Footwear",
      price: 69.99,
      cost: 64.95,
    },
    {
      sku: "SK13248",
      label: "Oversized Hoodie",
      class: "Outerwear",
      department: "Men's Apparel",
      price: 124.99,
      cost: 23.25,
    },
    {
      sku: "SK13498",
      label: "Unisex Oversized Sweatshirt",
      class: "Jewelry",
      department: "Men's Apparel",
      price: 139.99,
      cost: 77.13,
    },
    {
      sku: "SK13532",
      label: "Puffer Insulated Vest",
      class: "Tops",
      department: "Sportswear",
      price: 14.99,
      cost: 10.72,
    },
    {
      sku: "SK13740",
      label: "Faux Fur Winter Coat",
      class: "Outerwear",
      department: "Footwear",
      price: 14.99,
      cost: 4.56,
    },
    {
      sku: "SK13952",
      label: "Tactical Hiking Backpack",
      class: "Accessories",
      department: "Footwear",
      price: 199.99,
      cost: 115.79,
    },
    {
      sku: "SK14045",
      label: "Stretch Fit Slip-On Sneakers",
      class: "Accessories",
      department: "Unisex Accessories",
      price: 124.99,
      cost: 54.12,
    },
    {
      sku: "SK14051",
      label: "Crew Neck Merino Wool Sweater",
      class: "Tops",
      department: "Women's Apparel",
      price: 19.99,
      cost: 3.62,
    },
    {
      sku: "SK14104",
      label: "Handcrafted Wooden Watch",
      class: "Bottoms",
      department: "Footwear",
      price: 154.99,
      cost: 122.91,
    },
    {
      sku: "SK14223",
      label: "Smart Heated Gloves",
      class: "Tops",
      department: "Women's Apparel",
      price: 34.99,
      cost: 4.13,
    },
    {
      sku: "SK14232",
      label: "Luxury Silk Tie",
      class: "Tops",
      department: "Sportswear",
      price: 114.99,
      cost: 49.68,
    },
    {
      sku: "SK14409",
      label: "Heavy-Duty Work Gloves",
      class: "Tops",
      department: "Women's Apparel",
      price: 164.99,
      cost: 63.03,
    },
    {
      sku: "SK14424",
      label: "Waterproof Hiking Boots",
      class: "Jewelry",
      department: "Men's Apparel",
      price: 144.99,
      cost: 17.25,
    },
    {
      sku: "SK14528",
      label: "Performance Swim Trunks",
      class: "Footwear",
      department: "Unisex Accessories",
      price: 114.99,
      cost: 41.51,
    },
    {
      sku: "SK14566",
      label: "Feather Embellished Fedora",
      class: "Outerwear",
      department: "Sportswear",
      price: 184.99,
      cost: 193.87,
    },
    {
      sku: "SK14651",
      label: "Floral Chiffon Wrap Dress",
      class: "Tops",
      department: "Footwear",
      price: 159.99,
      cost: 110.23,
    },
    {
      sku: "SK14807",
      label: "Bamboo Fiber Boxer Briefs",
      class: "Accessories",
      department: "Men's Apparel",
      price: 89.99,
      cost: 7.74,
    },
    {
      sku: "SK14940",
      label: "Woven Straw Sun Hat",
      class: "Footwear",
      department: "Women's Apparel",
      price: 99.99,
      cost: 9.7,
    },
    {
      sku: "SK14945",
      label: "Silk Embroidered Kimono",
      class: "Bottoms",
      department: "Women's Apparel",
      price: 74.99,
      cost: 12.3,
    },
    {
      sku: "SK14974",
      label: "Asymmetrical Hem Skirt",
      class: "Bottoms",
      department: "Footwear",
      price: 184.99,
      cost: 19.98,
    },
    {
      sku: "SK15217",
      label: "Wool Fedora Hat",
      class: "Footwear",
      department: "Sportswear",
      price: 99.99,
      cost: 86.49,
    },
    {
      sku: "SK15290",
      label: "Fleece Jogger Sweatpants",
      class: "Footwear",
      department: "Sportswear",
      price: 79.99,
      cost: 45.67,
    },
    {
      sku: "SK15291",
      label: "Cuffed Jogger Pants",
      class: "Outerwear",
      department: "Sportswear",
      price: 114.99,
      cost: 52.9,
    },
    {
      sku: "SK15526",
      label: "Relaxed Fit Cargo Pants",
      class: "Bottoms",
      department: "Women's Apparel",
      price: 199.99,
      cost: 80.8,
    },
    {
      sku: "SK15631",
      label: "Velvet Slip Dress",
      class: "Tops",
      department: "Footwear",
      price: 164.99,
      cost: 106.75,
    },
    {
      sku: "SK15722",
      label: "Cashmere Turtleneck Sweater",
      class: "Accessories",
      department: "Men's Apparel",
      price: 99.99,
      cost: 91.79,
    },
    {
      sku: "SK15739",
      label: "High-Waisted Bikini Set",
      class: "Outerwear",
      department: "Sportswear",
      price: 64.99,
      cost: 69.34,
    },
    {
      sku: "SK15761",
      label: "Minimalist Gold Necklace",
      class: "Jewelry",
      department: "Sportswear",
      price: 74.99,
      cost: 71.47,
    },
    {
      sku: "SK16210",
      label: "Oversized Cat-Eye Sunglasses",
      class: "Outerwear",
      department: "Men's Apparel",
      price: 119.99,
      cost: 117.83,
    },
    {
      sku: "SK16364",
      label: "Minimalist Silver Ring",
      class: "Outerwear",
      department: "Women's Apparel",
      price: 64.99,
      cost: 49.59,
    },
    {
      sku: "SK16370",
      label: "Sherpa Lined Denim Jacket",
      class: "Jewelry",
      department: "Men's Apparel",
      price: 189.99,
      cost: 28.69,
    },
    {
      sku: "SK16474",
      label: "Cropped Faux Leather Jacket",
      class: "Outerwear",
      department: "Women's Apparel",
      price: 39.99,
      cost: 21.03,
    },
    {
      sku: "SK16642",
      label: "Tassel Fringe Handbag",
      class: "Tops",
      department: "Men's Apparel",
      price: 134.99,
      cost: 20.79,
    },
    {
      sku: "SK16722",
      label: "Reflective Running Vest",
      class: "Jewelry",
      department: "Sportswear",
      price: 154.99,
      cost: 112.21,
    },
    {
      sku: "SK16745",
      label: "Classic Denim Jacket",
      class: "Footwear",
      department: "Footwear",
      price: 24.99,
      cost: 22.29,
    },
    {
      sku: "SK16750",
      label: "Faux Leather Leggings",
      class: "Outerwear",
      department: "Unisex Accessories",
      price: 64.99,
      cost: 43.02,
    },
    {
      sku: "SK16871",
      label: "Woven Straw Sun Hat",
      class: "Bottoms",
      department: "Sportswear",
      price: 9.99,
      cost: 0.8,
    },
    {
      sku: "SK17623",
      label: "Silk Embroidered Kimono",
      class: "Footwear",
      department: "Footwear",
      price: 134.99,
      cost: 48.06,
    },
    {
      sku: "SK17867",
      label: "High-Slit Maxi Dress",
      class: "Tops",
      department: "Unisex Accessories",
      price: 9.99,
      cost: 7.85,
    },
    {
      sku: "SK18018",
      label: "Fleece-Lined Parka",
      class: "Tops",
      department: "Footwear",
      price: 59.99,
      cost: 17.4,
    },
    {
      sku: "SK18148",
      label: "Silk Neck Scarf",
      class: "Bottoms",
      department: "Men's Apparel",
      price: 114.99,
      cost: 120.62,
    },
    {
      sku: "SK18224",
      label: "Unisex Oversized Sweatshirt",
      class: "Accessories",
      department: "Men's Apparel",
      price: 134.99,
      cost: 106.64,
    },
    {
      sku: "SK18623",
      label: "Textured Knit Pullover",
      class: "Jewelry",
      department: "Men's Apparel",
      price: 34.99,
      cost: 33.38,
    },
    {
      sku: "SK18665",
      label: "Luxury Silk Tie",
      class: "Tops",
      department: "Footwear",
      price: 54.99,
      cost: 20.95,
    },
    {
      sku: "SK18753",
      label: "Rugged Utility Jacket",
      class: "Outerwear",
      department: "Women's Apparel",
      price: 29.99,
      cost: 20.69,
    },
    {
      sku: "SK18791",
      label: "Retro-Inspired Sunglasses",
      class: "Jewelry",
      department: "Unisex Accessories",
      price: 79.99,
      cost: 82.55,
    },
    {
      sku: "SK19521",
      label: "High-Slit Maxi Dress",
      class: "Outerwear",
      department: "Footwear",
      price: 14.99,
      cost: 6.49,
    },
    {
      sku: "SK19547",
      label: "Boho Style Tassel Earrings",
      class: "Outerwear",
      department: "Men's Apparel",
      price: 104.99,
      cost: 11.02,
    },
    {
      sku: "SK19857",
      label: "Metallic Hoop Earrings",
      class: "Bottoms",
      department: "Unisex Accessories",
      price: 84.99,
      cost: 35.61,
    },
  ]);
  const [skuDef] = useState<any>([
    { field: "sku", flex: 1 },
    { field: "label", flex: 1 },
    { field: "class", flex: 1 },
    { field: "department", flex: 1 },
    { field: "price", flex: 1 },
    { field: "cost", flex: 1 },
  ]);
  //sku data ends here

  //planning data starts here

  const [planningData] = useState<any>([
    { Store: "ST035", SKU: "SK00158", Week: "W01", "Sales Units": 58 },
    { Store: "ST035", SKU: "SK00158", Week: "W07", "Sales Units": 107 },
    { Store: "ST035", SKU: "SK00158", Week: "W09", "Sales Units": 0 },
    { Store: "ST035", SKU: "SK00158", Week: "W11", "Sales Units": 92 },
    { Store: "ST035", SKU: "SK00158", Week: "W13", "Sales Units": 122 },
    { Store: "ST035", SKU: "SK00158", Week: "W15", "Sales Units": 38 },
    { Store: "ST035", SKU: "SK00158", Week: "W23", "Sales Units": 88 },
    { Store: "ST035", SKU: "SK00158", Week: "W31", "Sales Units": 45 },
    { Store: "ST035", SKU: "SK00158", Week: "W35", "Sales Units": 197 },
    { Store: "ST035", SKU: "SK00158", Week: "W50", "Sales Units": 133 },
    { Store: "ST035", SKU: "SK00269", Week: "W05", "Sales Units": 107 },
    { Store: "ST035", SKU: "SK00269", Week: "W06", "Sales Units": 104 },
    { Store: "ST035", SKU: "SK00269", Week: "W09", "Sales Units": 32 },
    { Store: "ST035", SKU: "SK00269", Week: "W18", "Sales Units": 174 },
    { Store: "ST035", SKU: "SK00269", Week: "W23", "Sales Units": 174 },
    { Store: "ST035", SKU: "SK00269", Week: "W27", "Sales Units": 37 },
    { Store: "ST035", SKU: "SK00269", Week: "W28", "Sales Units": 95 },
    { Store: "ST035", SKU: "SK00269", Week: "W29", "Sales Units": 161 },
    { Store: "ST035", SKU: "SK00269", Week: "W30", "Sales Units": 175 },
    { Store: "ST035", SKU: "SK00269", Week: "W32", "Sales Units": 200 },
    { Store: "ST035", SKU: "SK00269", Week: "W33", "Sales Units": 120 },
    { Store: "ST035", SKU: "SK00269", Week: "W51", "Sales Units": 167 },
    { Store: "ST035", SKU: "SK00300", Week: "W14", "Sales Units": 135 },
    { Store: "ST035", SKU: "SK00300", Week: "W15", "Sales Units": 42 },
    { Store: "ST035", SKU: "SK00300", Week: "W41", "Sales Units": 185 },
    { Store: "ST035", SKU: "SK00300", Week: "W46", "Sales Units": 38 },
    { Store: "ST035", SKU: "SK00300", Week: "W50", "Sales Units": 149 },
    { Store: "ST035", SKU: "SK00304", Week: "W16", "Sales Units": 40 },
    { Store: "ST035", SKU: "SK00304", Week: "W18", "Sales Units": 140 },
    { Store: "ST035", SKU: "SK00304", Week: "W19", "Sales Units": 200 },
    { Store: "ST035", SKU: "SK00304", Week: "W23", "Sales Units": 108 },
    { Store: "ST035", SKU: "SK00304", Week: "W36", "Sales Units": 28 },
    { Store: "ST035", SKU: "SK00304", Week: "W42", "Sales Units": 11 },
    { Store: "ST035", SKU: "SK00304", Week: "W47", "Sales Units": 42 },
    { Store: "ST035", SKU: "SK00766", Week: "W04", "Sales Units": 167 },
    { Store: "ST035", SKU: "SK00766", Week: "W08", "Sales Units": 143 },
    { Store: "ST035", SKU: "SK00766", Week: "W10", "Sales Units": 120 },
    { Store: "ST035", SKU: "SK00766", Week: "W12", "Sales Units": 21 },
    { Store: "ST035", SKU: "SK00766", Week: "W13", "Sales Units": 92 },
    { Store: "ST035", SKU: "SK00766", Week: "W14", "Sales Units": 141 },
    { Store: "ST035", SKU: "SK00766", Week: "W15", "Sales Units": 108 },
    { Store: "ST035", SKU: "SK00766", Week: "W19", "Sales Units": 167 },
    { Store: "ST035", SKU: "SK00766", Week: "W21", "Sales Units": 1 },
    { Store: "ST035", SKU: "SK00766", Week: "W42", "Sales Units": 63 },
    { Store: "ST035", SKU: "SK00766", Week: "W44", "Sales Units": 179 },
    { Store: "ST035", SKU: "SK00766", Week: "W49", "Sales Units": 110 },
    { Store: "ST035", SKU: "SK00786", Week: "W02", "Sales Units": 100 },
    { Store: "ST035", SKU: "SK00786", Week: "W05", "Sales Units": 16 },
    { Store: "ST035", SKU: "SK00786", Week: "W09", "Sales Units": 76 },
  ]);

  const [planningDataDef] = useState<any>([
    { field: "Store", flex: 1 },
    { field: "SKU", flex: 1 },
    { field: "Week", flex: 1 },
    { field: "Sales Units", flex: 1 },
  ]);
  // planning data ends here

  //calender data starts here
  const [calenderData] = useState<any>([
    { week: "W01", weekLabel: "Week 01", month: "M01", monthLabel: "Feb" },
    { week: "W02", weekLabel: "Week 02", month: "M01", monthLabel: "Feb" },
    { week: "W03", weekLabel: "Week 03", month: "M01", monthLabel: "Feb" },
    { week: "W04", weekLabel: "Week 04", month: "M01", monthLabel: "Feb" },
    { week: "W05", weekLabel: "Week 05", month: "M02", monthLabel: "Mar" },
    { week: "W06", weekLabel: "Week 06", month: "M02", monthLabel: "Mar" },
    { week: "W07", weekLabel: "Week 07", month: "M02", monthLabel: "Mar" },
    { week: "W08", weekLabel: "Week 08", month: "M02", monthLabel: "Mar" },
    { week: "W09", weekLabel: "Week 09", month: "M02", monthLabel: "Mar" },
    { week: "W10", weekLabel: "Week 10", month: "M03", monthLabel: "Apr" },
    { week: "W11", weekLabel: "Week 11", month: "M03", monthLabel: "Apr" },
    { week: "W12", weekLabel: "Week 12", month: "M03", monthLabel: "Apr" },
    { week: "W13", weekLabel: "Week 13", month: "M03", monthLabel: "Apr" },
    { week: "W14", weekLabel: "Week 14", month: "M04", monthLabel: "May" },
    { week: "W15", weekLabel: "Week 15", month: "M04", monthLabel: "May" },
    { week: "W16", weekLabel: "Week 16", month: "M04", monthLabel: "May" },
    { week: "W17", weekLabel: "Week 17", month: "M04", monthLabel: "May" },
    { week: "W18", weekLabel: "Week 18", month: "M05", monthLabel: "Jun" },
    { week: "W19", weekLabel: "Week 19", month: "M05", monthLabel: "Jun" },
    { week: "W20", weekLabel: "Week 20", month: "M05", monthLabel: "Jun" },
    { week: "W21", weekLabel: "Week 21", month: "M05", monthLabel: "Jun" },
    { week: "W22", weekLabel: "Week 22", month: "M05", monthLabel: "Jun" },
    { week: "W23", weekLabel: "Week 23", month: "M06", monthLabel: "Jul" },
    { week: "W24", weekLabel: "Week 24", month: "M06", monthLabel: "Jul" },
    { week: "W25", weekLabel: "Week 25", month: "M06", monthLabel: "Jul" },
    { week: "W26", weekLabel: "Week 26", month: "M06", monthLabel: "Jul" },
    { week: "W27", weekLabel: "Week 27", month: "M07", monthLabel: "Aug" },
    { week: "W28", weekLabel: "Week 28", month: "M07", monthLabel: "Aug" },
    { week: "W29", weekLabel: "Week 29", month: "M07", monthLabel: "Aug" },
    { week: "W30", weekLabel: "Week 30", month: "M07", monthLabel: "Aug" },
    { week: "W31", weekLabel: "Week 31", month: "M08", monthLabel: "Sep" },
    { week: "W32", weekLabel: "Week 32", month: "M08", monthLabel: "Sep" },
    { week: "W33", weekLabel: "Week 33", month: "M08", monthLabel: "Sep" },
    { week: "W34", weekLabel: "Week 34", month: "M08", monthLabel: "Sep" },
    { week: "W35", weekLabel: "Week 35", month: "M08", monthLabel: "Sep" },
    { week: "W36", weekLabel: "Week 36", month: "M09", monthLabel: "Oct" },
    { week: "W37", weekLabel: "Week 37", month: "M09", monthLabel: "Oct" },
    { week: "W38", weekLabel: "Week 38", month: "M09", monthLabel: "Oct" },
    { week: "W39", weekLabel: "Week 39", month: "M09", monthLabel: "Oct" },
    { week: "W40", weekLabel: "Week 40", month: "M10", monthLabel: "Nov" },
    { week: "W41", weekLabel: "Week 41", month: "M10", monthLabel: "Nov" },
    { week: "W42", weekLabel: "Week 42", month: "M10", monthLabel: "Nov" },
    { week: "W43", weekLabel: "Week 43", month: "M10", monthLabel: "Nov" },
    { week: "W44", weekLabel: "Week 44", month: "M11", monthLabel: "Dec" },
    { week: "W45", weekLabel: "Week 45", month: "M11", monthLabel: "Dec" },
    { week: "W46", weekLabel: "Week 46", month: "M11", monthLabel: "Dec" },
    { week: "W47", weekLabel: "Week 47", month: "M11", monthLabel: "Dec" },
    { week: "W48", weekLabel: "Week 48", month: "M11", monthLabel: "Dec" },
    { week: "W49", weekLabel: "Week 49", month: "M12", monthLabel: "Jan" },
    { week: "W50", weekLabel: "Week 50", month: "M12", monthLabel: "Jan" },
    { week: "W51", weekLabel: "Week 51", month: "M12", monthLabel: "Jan" },
    { week: "W52", weekLabel: "Week 52", month: "M12", monthLabel: "Jan" },
  ]);

  const [calenderDataDef] = useState<any>([
    {
      headerName: "S.No.",
      valueGetter: "node.rowIndex + 1",
    },
    {
      headerName: "S.No.",
      valueGetter: "node.rowIndex + 1",
    },
    { field: "week", flex: 1 },
    { field: "weekLabel", flex: 1 },
    { field: "month", flex: 1 },
    { field: "monthLabel", flex: 1 },
  ]);
  return (
    <div style={{ height: "calc(100vh - 150px)", width: "100%" }}>
      <AgGridReact rowData={storeRowData} columnDefs={storeColDefs} />
    </div>
  );
}

export default AgChart;
